version: "3"
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: hippymood
      MYSQL_USER: hippymood_user
      MYSQL_PASSWORD: hippymood_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    # Making database data persistent
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql:z"
  app:
    build: .
    links:
      - mariadb
    ports:
      - "8080:8080"
    volumes:
      - "./:/app/:z"
      # - "/path/to/your/music/library:/app/music:z"
