version: "3"
services:
 mariadb:
  container_name: mariadb
  image: mariadb
  environment:
   MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
   MYSQL_DATABASE: hippymood
   MYSQL_USER: hippymood_user
   MYSQL_PASSWORD: hippymood_password
  ports:
   - "3307:3306"
  volumes:
    - "./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql:z"
  restart: always
 app:
  container_name: hippymood
  build: .
  links:
   - mariadb
  ports:
   - "8080:8080"
  volumes:
    - "/home/ronan/music:/app/music:z"
  command: ["./docker-wait-for-mariadb.sh", "mariadb", "npm", "run", "dev"]
