mariadb:
 container_name: mariadb
 image: mariadb
 environment:
  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  MYSQL_DATABASE: hippymood
  MYSQL_USER: hippymood_user
  MYSQL_PASSWORD: hippymood_password
 ports:
  - "3307:3306"
 restart: always
app:
 build: .
 links:
  - mariadb
 ports:
  - "8080:8080"
 command: ["./docker-wait-for-mariadb.sh", "mariadb"]
