version: "2"
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: hippymood
      MYSQL_USER: hippymood_user
      MYSQL_PASSWORD: hippymood_password
    networks:
      - dev-network
    ports:
      - "3306:3306"
    # Making database data persistent
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql:z"
    restart: always
  app:
    build: .
    command: ["./docker/wait-for-mariadb.sh", "mariadb", "npm", "run", "dev"]
    #entrypoint: /app/docker/docker-entrypoint.sh dev
    entrypoint: /app/docker/docker-entrypoint.sh perf flame
    links:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:hippymood.localhost
      - traefik.port=8082
      - traefik.docker.network=dev-network
    networks:
      - dev-network
    ports:
      - "8082:8082"
    volumes:
      - "./:/app/:z"
      - "./config/server.config.js:/app/config/server.config.js:z"
      #- "/path/to/your/music/library:/app/music:z"
      - "/home/ronan/music:/app/music:z"

networks:
  dev-network:
    external: true
