version: "3.7"

services:
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: hippymood
      MYSQL_USER: hippymood_user
      MYSQL_PASSWORD: hippymood_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  backend:
    image: node:12-stretch
    command: npm run start
    environment:
      NODE_CONFIG_DIR: '../config'
    links:
      - mariadb
    depends_on:
      - mariadb

  frontend:
    image: node:12-stretch
    command: npm run serve
    environment:
      NODE_CONFIG_DIR: '../config'
    links:
      - backend
    depends_on:
      - backend
    pid: "host"
