version: "2"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: hippymood
      MYSQL_USER: hippymood_user
      MYSQL_PASSWORD: hippymood_password
    # Making database data persistent
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql:z"
  app:
    build: .
    links:
      - mariadb
    ports:
      - "8086:80"
    command: ["./docker/wait-for-mariadb.sh", "dev"]
    entrypoint: /app/docker/docker-entrypoint.sh dev
