version: "3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: plopiplop
      MYSQL_DATABASE: hippymood
      MYSQL_USER: hippymood_user
      MYSQL_PASSWORD: hippymood_password
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql:z"
    restart: always
  app:
    container_name: hippymood
    build: .
    links:
      - mariadb
    ports:
      - "8080:8080"
    volumes:
      - ".:/app:z"
      - "/home/ronan/music:/app/music:z"
    command: ["./docker/wait-for-mariadb.sh", "mariadb", "npm", "run", "dev"]
    #command: ["./docker/wait-for-mariadb.sh", "mariadb", "npm", "run", "prod"]
