version: "3.7"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: hippymood
      POSTGRES_USER: hippymood_user
      POSTGRES_PASSWORD: hippymood_password
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'

  backend:
    image: node:12-stretch
    command: npm run start
    environment:
      NODE_CONFIG_DIR: '../config'
    links:
      - db
    depends_on:
      - db

  frontend:
    image: node:12-stretch
    command: npm run serve
    environment:
      NODE_CONFIG_DIR: '../config'
    links:
      - backend
    depends_on:
      - backend
    pid: "host"
