version: "2"
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: hippymood
      MYSQL_USER: hippymood_user
      MYSQL_PASSWORD: hippymood_password
    # Making database data persistent
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql:z"
    restart: always
  app:
    build: .
    container_name: hippymood_dev
    links:
      - mariadb
    ports:
      - "8086:80"
    volumes:
      - ".:/app:z"
      - "/path/to/your/music/library:/app/music:z"
    entrypoint: /app/docker/docker-entrypoint.sh dev
    command: ["./docker/wait-for-mariadb.sh", "mariadb", "npm", "run", "dev"]
